### ISSUE TITLE
404 at https://docs.korge.org/korge/setup

### ISSUE THREAD

**Issue by RedFT** [korlibs/docs.korge.org#81]
https://docs.korge.org/korge/setup

**Comment by RedFT** [comment]
Thanks for creating/maintaining this project! Just wanted to play around with it a bit. 

I'm looking at https://github.com/korlibs/docs.korge.org/blob/master/%40old/korge/setup/index.md for now.

**Comment by soywiz** [comment]
New link should be this one: https://docs.korge.org/korge/gettingstarted/setup/

In order to fix it: where did you found the broken link?

**Comment by RedFT** [comment]
> In order to fix it: where did you found the broken link?

Right here under tools: https://docs.korge.org/korge/
